### ISSUE TITLE
Cannot resolve .war with wildfly-server-provisioning-maven-plugin 1.2.7+

### ISSUE THREAD

**Issue by shawkins** [wildfly/wildfly-build-tools#47]
With 1.2.7+ in our build we get the error:

[ERROR] Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.2.7.Final:build (dist-provisioning) on project teiid: Execution dist-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.2.7.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: Could not resolve artifact org.teiid:teiid-olingo::odata4 to copy -> [Help 1]

This is coming from the feature pack build file: https://github.com/teiid/teiid/blob/master/teiid-feature-pack/olingo-feature-pack/feature-pack-build.xml

It is attempting to referencing a war artifact by the classifier, which works in 1.2.1 and prior releases.

**Comment by jamezp** [comment]
This plugin has been deprecated and [Galleon](https://docs.wildfly.org/galleon/) should now be used.
