### ISSUE TITLE
Make thread safe "wildfly-feature-pack-build-maven-plugin"

### ISSUE THREAD

**Issue by rady66** [wildfly/wildfly-build-tools#52]
Please make "wildfly-feature-pack-build-maven-plugin" thread safe so we can get rid of those warnings during parallel build (mvn clean install -T 1C).

[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe

**Comment by jamezp** [comment]
This plugin has been deprecated and [Galleon](https://docs.wildfly.org/galleon/) should now be used.
