### ISSUE TITLE
Exception when provisioning Wildfly Preview 24.0.1.Final

### ISSUE THREAD

**Issue by Faliorn** [wildfly/wildfly-build-tools#57]
Hi! My name is Alex, and I have been using the wildfly provisioning tool since Wildfly 23, and it works great!

However, now I need to work with Wildfly **Preview** 24.0.1.Final, and when I tried to do it, I get this error:

`Failed to create feature pack from org.wildfly:wildfly-preview-feature-pack:zip::24.0.1.Final: feature pack description not found`

I've tried to debug the problem, and I believe it could have something to do with "wildfly-preview-feature-pack-24.0.1.Final.zip", and the `feature-pack.xml` file. I think plugin expects a `wildfly-feature-pack.xml` instead. However, I've also tried renaming it and I get a different error.

Maybe I'm doing something wrong? I'm attaching the files I use for provisioning.

Thanks and keep up the good work!
[wildfly-provisioning.zip](https://github.com/wildfly/wildfly-build-tools/files/7154119/wildfly-provisioning.zip)

**Comment by jamezp** [comment]
This plugin is essentially deprecated. Are you trying to provision a server? If so you'd want to use the `org.jboss.galleon:galleon-maven-plugin`. For WildFly Preview it would look something like:

```
<plugin>
    <groupId>org.jboss.galleon</groupId>
    <artifactId>galleon-maven-plugin</artifactId>
    <configuration>
        <install-dir>${jboss.home}</install-dir>
        <record-state>true</record-state>
        <plugin-options>
            <jboss-fork-embedded>true</jboss-fork-embedded>
            <jboss-jakarta-transform-artifacts>true</jboss-jakarta-transform-artifacts>
        </plugin-options>
        <feature-packs>
            <feature-pack>
                <groupId>org.wildfly</groupId>
                <artifactId>wildfly-preview-feature-pack</artifactId>
                <version>${project.version}</version>
                <inherit-configs>true</inherit-configs>
            </feature-pack>
        </feature-packs>
    </configuration>
    <executions>
        <execution>
            <id>server-provisioning</id>
            <phase>generate-test-resources</phase>
            <goals>
                <goal>provision</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

There is some work being done on making it easier.  You can also do it with a command line too as well. There is some more information here. https://docs.wildfly.org/galleon/
